let allTools = [
    "Angle",
    "ArrowAnnotate",
    "Bidirectional",
    "Brush",
    "CircleRoi",
    "CircleScissors",
    "CobbAngle",
    "CorrectionScissors",
    "Crosshairs",//2
    "DoubleTapFitToWindow", //1
    "DragProbe",
    "EllipticalRoi",
    "Eraser",
    "FreehandRoiSculptor",
    "FreehandRoi",
    "FreehandScissors",
    "Length",
    "Magnify",
    "OrientationMarkers",
    "Overlay",
    "PanMultiTouch",
    "Pan",
    "Probe",
    "RectangleRoi",
    "RectangleScissors",
    "ReferenceLines",
    "Rotate",
    "RotateTouch",
    "SaveAs",
    "ScaleOverlay",
    "SphericalBrush",
    "StackScrollMouseWheel",
    "StackScrollMultiTouch",
    "StackScroll",
    "Synchronizer",
    "TextMarker",
    "WwwcRegion",
    "Wwwc",
    "ZoomMouseWheel",
    "Zoom",
    "ZoomTouchPinch",

    "InvertColorTool"
]

export {allTools}